apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    
    spec:
      containers:
        - name: fastapi
          image: gaddock/week11_proj:v1.7
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD
          envFrom:
            - configMapRef:
                name: api-configmap   